### ISSUE TITLE
Response_code

### ISSUE THREAD

**Issue by Dbinformatique69** [TrogloGeek/prestashop-tggatos-module#100]
Bonjour

Dans une transation, j'ai "response_code: 05". A quoi correspond ce code (05)?
le libellé est "Autorisation acceptée de PayPal", Hors, nous ne proposons pas l'option "Paypal"
Très cordialement
Didier BRUN

**Comment by TrogloGeek** [comment]
De mémoire (a vérifier dans la documentation SIPS) il me semble qu'il s'agit du code de refus de la transaction.
Pour ce qui est du libellé, je suppose qu'il s'agit du libellé de statut de commande, auquel cas je pense qu'il serait temps de vérifier la configuration des statut de commande associés au différents cas (succès, annulation, refus) dans la page de configuration du module, il est possible qu'une mise à jour de PrestaShop ait changé les identifiants de statuts de commande ce qui aura désynchronisé la configuration du module.

**Comment by Dbinformatique69** [comment]
Merci de cette réponse, c'est ok pour moi 

Didier

**Comment by TrogloGeek** [comment]
Merci pour le retour :-)
