### ISSUE TITLE
Exécutables incompatibles Debian 10 "Buster"

### ISSUE THREAD

**Issue by feloot** [TrogloGeek/prestashop-tggatos-module#102]
Bonjour,

Sur Debian 10 nous obtenons une erreur segfault 139 en exécutant les binaires. La même opération sur Debian 9 s'exécute sans problème ; tout cela en ligne de commande.

Je sais que cela relève de la banque et non du module Tggatos mais j'ai téléchargé les derniers binaires chez notre banque et nous avons toujours le souci ; donc je pose la question ici au cas où, est-ce que quelqu'un aurait rencontré ce problème également et aurait trouvé une solution ?

Merci

**Comment by TrogloGeek** [comment]
Bonjour,
Ça sent le binaire corrompus par un transfert FTP en mode TEXT.

**Comment by feloot** [comment]
J'y ai pensé aussi mais je suis bien en binaire sur FileZilla, j'upload les mêmes fichiers de la même manière et au même endroit sur les 2 serveurs et comme je disais c'est OK sur Debian 9 mais pas sur 10. J'ai essayé les fichiers proposés par la banque et ceux par défaut sur le module et j'ai le même souci partout. J'ai également testé en faisant un rsync d'un serveur à l'autre.

Avez-vous déjà pu tester les exécutables sur Debian 10 et si oui est-ce que ça fonctionne chez vous ? Ça me permettrait d'exclure l'hypothèse de l'incompatibilité système si effectivement ce n'est pas ça.

Merci

**Comment by TrogloGeek** [comment]
Dans ce cas je suspecte que vous utilisez les binaires compilés dynamiquement (utilise la libc du système) et qu'il y a incompatibilité. Essayez avec la version en compilation statique. Il prennent plus d'espace mémoire mais ça ne devrait pas être un drame vu le peu de temps que dure leur exécution.

Non je n'ai pas testé sous un kernel aussi récent, il y a bien longtemps que je n'ai pas eu moi même à toucher à du SIPS hors des tests du module sur VM, la dernière fois doit remonter à du Debian 9.

**Comment by feloot** [comment]
Bien vu ! Cela a fonctionné.

Merci énormément.
