### ISSUE TITLE
Executables incompatibles avec debian 10

### ISSUE THREAD

**Issue by PhilFer101** [TrogloGeek/prestashop-tggatos-module#104]
Bonjour
J'ai moi aussi le code erreur 139 sur les executables avec mon nouveau serveur sous debian 10.
Dans un précédent échange, il est indiqué : "Dans ce cas je suspecte que vous utilisez les binaires compilés dynamiquement (utilise la libc du système) et qu'il y a incompatibilité. Essayez avec la version en compilation statique. Il prennent plus d'espace mémoire mais ça ne devrait pas être un drame vu le peu de temps que dure leur exécution."
Et il semble que cela ait fonctionné.
Mais où peut-on trouvé cette version compilées en statique ?
Merci d'avance

**Comment by TrogloGeek** [comment]
Bonjour, vous n'êtes pas censé utiliser les binaires présents dans le module, qui ne sont là qu'à des fins de testabilité d'une release. Vous devez utiliser les binaires fournis par votre prestataire de service SIPS (généralement: banque).
