### ISSUE TITLE
Prestashop 1.7.6.4 installation not possible

### ISSUE THREAD

**Issue by febrez** [TrogloGeek/prestashop-tggatos-module#105]
Hello, I tried to install the module without success (ftp upload, even from admin)

Module versions that I tried to install : 4.1.3 / 5.0.0-b2

**Comment by TrogloGeek** [comment]
Hi, did you rename the folder to "tggatos" ?
Main module file should be found at prestashop/modules/tggatos/tggatos.php.
By the way there is a 5.1.0 branch available.

**Comment by febrez** [comment]
Module 5.1.0 is working :) 

I've replaced the line 224 in tggatos.php according to my prestashop version :

`$this->ps_versions_compliancy['max'] = '1.7.6.4';`

Thank you
