### ISSUE TITLE
Error when calling request binary, system exit code: 139, text output:

### ISSUE THREAD

**Issue by Dbinformatique69** [TrogloGeek/prestashop-tggatos-module#109]
Hello 
In my prestashop 1.6.1
I have ths issue 
Error when calling request binary, system exit code: 139, text output:

Best regards

Didier

**Comment by TrogloGeek** [comment]
Hi, you either forgot to replace SIPS binaries with compatible ones from your bank, did not set rights for PHP process user to execute them, corrupted them using ASCII FTP transfer or placed them outside open_basedir allowed paths.
