### ISSUE TITLE
Bug - Amount multiplied by 100 when payment failure

### ISSUE THREAD

**Issue by theben22** [TrogloGeek/prestashop-tggatos-module#11]
Hello all,

When payment failure, the amount showed comes from parameter of request and thus is multiplied by 100 (916€ instead of 9,16€ for instance).

If you do not want to afraid customers, it is better to modify views/templates/front/payment_failure.tpl file.
You have to change line 65 from <td>{$tggatos_response->amount}</td> to <td>{$tggatos_response->amount/100}</td>
That is no really clean but it works.

Regards,

**Comment by e-gaulue** [comment]
I confirm, thank for the hack !

**Comment by TrogloGeek** [comment]
This is no bug, it displays amount in the lowest currency unit (the way ATOS SIPS works).
Anyway, last commit changed this.
0c88f9d14b20e741b7ae7b478905f2065336c709

**Comment by e-gaulue** [comment]
You have the same behavior in the "log" message linked to the command.

**Comment by TrogloGeek** [comment]
This is a developer choice : log message logs SIPS returned values, I want them as untouched as possible. If I would manipulate these data prior to log them, they would not be usable for debug purpose and would not be trustworthy.
