### ISSUE TITLE
Gap in transaction ID

### ISSUE THREAD

**Issue by theben22** [TrogloGeek/prestashop-tggatos-module#12]
Hello,

I saw a gap in transaction ID when cancelling a payment.

Here are detailled actions I did to get the bugg 
- ask to pay by credit card
- click on a credit card to make the scellius page appearing. On this page I noticed the transaction ID.
- cancel the payment and go back to the shop
- ask for another payment mode
- click again on a credit card. On scellius page I can see that transaction ID increaded.
- cancel again the payment and go back to the shop. In the shop, I see that the transaction ID is the first one.

Could you fix the problem when you'll have time ? Thank you.

Regards,

**Comment by TrogloGeek** [comment]
fixed, thank you very much for the report
