### ISSUE TITLE
Register the order payment 

### ISSUE THREAD

**Issue by e-gaulue** [TrogloGeek/prestashop-tggatos-module#14]
Maybe it's a misconfiguration here but in Prestashop 1.5 you can register the payments linked to the orders.

It needs the date, the means of payment, the transaction ID and the amount. I wondered if it would be possible to automatically register a card payment as we have all those informations.

**Comment by TrogloGeek** [comment]
You mean this ?
![cc-payment](https://f.cloud.github.com/assets/3205686/857355/4661444a-f54f-11e2-86e1-d0fa2d8096fb.png)

You even have a configuration option (advanced tab) to choose which transaction reference to register as PS transaction ID
![ps-transactionid-conf](https://f.cloud.github.com/assets/3205686/857394/0430e0de-f550-11e2-8b5d-5c5e81060ba5.png)

It works great on my instances (PS 1.5.1, PS 1.5.2), have you tried on a fresh install (fresh PS and fresh module)? If yes, please provide me with your PS version for me to try to reproduce the problem, I don't have time to test everything on every PS release, I don't earn money with this module, I just loose a lot of money and time ;-)
