### ISSUE TITLE
Invalid amount length

### ISSUE THREAD

**Issue by SylvainBigonneau** [TrogloGeek/prestashop-tggatos-module#19]
First of all, many thanks for this lovely module.

Apparently, there is a case missing in this module which generates an atos error: when the amount of the payment is inferior to 1€, tggatos does indeed multiply it by 100, but according to documentation, it should also append zeros behind the number in order to make it three digits long at least.

So right now, when I pay 0.95€, I get "invalid amount length (95)"

I wish I could provide a solution as well, but I have yet to find the place in the code where the price is expressed as a string and not as an int.

**Comment by TrogloGeek** [comment]
Thanks for pinpointing it, I was sure I already addressed this but enventually I didn't.
I owe you a beer, or two maybe.

**Comment by SylvainBigonneau** [comment]
The fix works like a charm, thank you for your prompt response.
