### ISSUE TITLE
Bug - Img tag is outside the link in the hook

### ISSUE THREAD

**Issue by Arkhee** [TrogloGeek/prestashop-tggatos-module#2]
It seems that in the "payment.tpl" in the "view => template => hook" folder the img should be inserted inside the link. Doing otherwise produces a result inconsistent with other payment modules :
![tggatos-pb-img](https://f.cloud.github.com/assets/3664145/192768/dbf9f93e-7f6b-11e2-9627-dcfc8c9962df.jpg)

**Comment by TrogloGeek** [comment]
You're right, thanks.
