### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kiero63** [TrogloGeek/prestashop-tggatos-module#23]
Bonjour,

J'utilise un prestashop 1.5.6.2 avec la dernière version du module. Le probleme est sur la page de paiement lorsque je valide ou que j'annule le paiement le retour se fait sur une erreur 500 sur le lien suivant http://mon_site.com/modules/tggatos/autodispatch/userreturn.pub.php
Je suis sur un mutualisé OVH si des fois ca peut expliquer le problème.

Merci

**Comment by TrogloGeek** [comment]
Bonjour,

Merci de fournir les logs d'erreurs correspondant à l'erreur.

**Comment by kiero63** [comment]
Je n'obtiens que ca comme information sur le log d'ovh  : 
90.38.126.49 mon_site.com - [05/Feb/2014:23:58:40 +0100] "POST /modules/tggatos/autodispatch/userreturn.pub.php HTTP/1.1" 500 351 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0"
J'ai également trouvé cette info dans les logs : [Wed Feb 05 23:58:40 2014] [error] [client 90.38.126.49] [host mon_site.com] Premature end of script headers: userreturn.pub.php

J'ai fait un test en me créant un fichier php a l'intérieur du dossier avec un simple  <?php echo "bonjour";  et j'obtiens une erreur 500 également. En le convertissant en html mon texte apparait enfin. J'avais édité le htaccess pour autoriser l'accès a ce type de fichier.

**Comment by kiero63** [comment]
Finalement, j'ai trouvé l'erreur. Le problème vient des droits, OVH n'autorise pas l'utilisation d'un chmod 777, c'est pour ca que mon répertoire était bloqué. Il faut que le dossier et les fichiers est un maximum de 755. Ca me parait intéressant de le préciser pour de futur utilisateur.
Idem pour les binaires, j'ai eu un code erreur 11 qui ne correspondait a rien de spécial et le probleme venait du mode de transfert de mon logiciel FTP, il a fallu que je change le transfert en mode binaire pour que cela marche.
