### ISSUE TITLE
Bug - Back to the shop after cancelling displays some sort of var_dump

### ISSUE THREAD

**Issue by Arkhee** [TrogloGeek/prestashop-tggatos-module#3]
Module is set up alright, the form appears when selecting the atos module, when clicking on a card the payment page, located on the bank server, appears with the right amount.

But if I cancel the payment the following message appears :

Array ( [received fields] => Array ( [0] => 04XXXXXXXXXXXXX [1] => fr [2] => 7470 [3] => 3 [4] => CB [5] => 20130225165648 [6] => [7] => [8] => 17 [9] => [10] => [11] => 978 [12] => [13] => [14] => [15] => [16] => [17] => [18] => [19] => [20] => [21] => fr [22] => fr [23] => 2 [24] => 195038 [25] => [26] => 89.157.12.18 [27] => [28] => [29] => [30] => 02 [31] => [32] => [33] => [34] => [35] => [36] => [37] => [38] => [39] => [40] => [41] => ) [known fields] => Array ( [0] => merchant_id [1] => merchant_country [2] => amount [3] => transaction_id [4] => payment_means [5] => transmission_date [6] => payment_time [7] => payment_date [8] => response_code [9] => payment_certificate [10] => authorisation_id [11] => currency_code [12] => card_number [13] => cvv_flag [14] => cvv_response_code [15] => bank_response_code [16] => complementary_code [17] => complementary_info [18] => return_context [19] => caddie [20] => receipt_complement [21] => merchant_language [22] => language [23] => customer_id [24] => order_id [25] => customer_email [26] => customer_ip_address [27] => capture_day [28] => capture_mode [29] => data ) )

I did not have time to reproduce this in an environment running xdebug yet.

**Comment by TrogloGeek** [comment]
Thanks for submitting.
This is not so much of a bug, but still a problem to fix: module right now is made with documentation that's been written a long time ago. As I am not client of any ATOS SIPS provider, I don't have access to more decent documentation, ones provided for now by many people are the same, I'm not sure they did update documentation along with updating binaries.
If you have documentation that describes supplementary fields of your response API version I'll add them.

**Comment by TrogloGeek** [comment]
After verification they was also a bug in short response handling.
You could try a64a196873a10bde32065968f2d637fae03db9bc, but I don't have time to test it yet.

**Comment by Arkhee** [comment]
Yes it worked ! Thanks a lot
After cancelling the payment the customer is redirected to the right page.
In test mode, using a wrong card number also worked, using a right card numer created the order.
All is left is the french translation ;) (for now)
