### ISSUE TITLE
transaction_ID

### ISSUE THREAD

**Issue by Nikusfr** [TrogloGeek/prestashop-tggatos-module#30]
Hello,
We are using your module with LCL, but when the payment it's not validate by the bank customer return to our website and try again to pay, the transaction id stay the same.

The LCL don't accept same paiement_id on day.

"Transaction déjà traitée (votre paiement n'a pas été accepté)
Nous regrettons de ne pouvoir donner suite à votre demande, merci de prendre contact directement avec le commerçant afin de terminer votre commande"

To solve this issue the customer needs to clear the browser cache.

Do you have solution ?

BR
Nicolas

**Comment by Nikusfr** [comment]
It was someting in this part of my htaccess, do you have issue

# ACTIVATION DU KEEP ALIVE

<IfModule mod_headers.c>
   Header set Connection keep-alive
</IfModule>

# ACTIVATION DE LA COMPRESSION DES PAGES

<IfModule mod_deflate.c>
SetOutputFilter DEFLATE
AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml text/javascript application/javascript application/x-javascript application/x-httpd-php

# POUR LES NAVIGATEURS INCOMPATIBLES

BrowserMatch ^Mozilla/4 gzip-only-text/html
BrowserMatch ^Mozilla/4.0[678] no-gzip
BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
BrowserMatch \bMSI[E] !no-gzip !gzip-only-text/html
#PAS DE COMPRESSION POUR LES FORMATS NE LE NECESSITANT PAS
SetEnvIfNoCase Request_URI .(?:gif|jpe?g|png)$ no-gzip
</IfModule>

# GESTION CORRECTE DES PROXIES

Header append Vary User-Agent env=!dont-vary

# GESTION DES DATES D'EXPIRATION POUR FAVORISER LE CACHE NAVIGATEUR

<IfModule mod_expires.c>
 ExpiresActive On
 ExpiresDefault "access plus 7200 seconds"
 ExpiresByType image/jpg "access plus 2592000 seconds"
 ExpiresByType image/jpeg "access plus 2592000 seconds"
 ExpiresByType image/png "access plus 2592000 seconds"
 ExpiresByType image/gif "access plus 2592000 seconds"
 AddType image/x-icon .ico
 ExpiresByType image/ico "access plus 2592000 seconds"
 ExpiresByType image/icon "access plus 2592000 seconds"
 ExpiresByType image/x-icon "access plus 2592000 seconds"
 ExpiresByType text/css "access plus 2592000 seconds"
 ExpiresByType text/javascript "access plus 2592000 seconds"
 ExpiresByType text/html "access plus 7200 seconds"
 ExpiresByType application/xhtml+xml "access plus 7200 seconds"
 ExpiresByType application/javascript A259200
 ExpiresByType application/x-javascript "access plus 2592000 seconds"
 ExpiresByType application/x-shockwave-flash "access plus 2592000 seconds"
</IfModule>

# MISE EN CACHE DES FICHIERS NON DYNAMIQUES : IMAGES, CSS, JAVASCRIPT...

<IfModule mod_headers.c>
 <FilesMatch "\\.(ico|jpe?g|JPE?G|png|gif|swf|css|gz)$">
 Header set Cache-Control "max-age=2592000, public"
 </FilesMatch>
 <FilesMatch "\\.(js)$">
 Header set Cache-Control "max-age=2592000, private"
 </FilesMatch>
<filesMatch "\\.(html|htm)$">
Header set Cache-Control "max-age=7200, public"
</filesMatch>

# SUPPRESSION DES ETAGS

Header unset ETag
FileETag none

**Comment by TrogloGeek** [comment]
Indeed, already seen the problem on some hosts that use by default an aggressive caching strategy, I've thought that I should enforce a no-caching strategy from the controller of my module, and then I forgot.
Thanks a lot for the reminder!
