### ISSUE TITLE
Silent Response is not working

### ISSUE THREAD

**Issue by loran750** [TrogloGeek/prestashop-tggatos-module#33]
Hello

I'm using Sogenactif and rC 3.40 on Prestashop 1.6.0.8.
When I disable "Force user return from bank" whis is related to data[NO_RESPONSE_PAGE], there is NO record in any step until I click on "return to the merchant site" button.

It means : if the visitor closes the windows on the Sogenactif website, nothing is written in the website, no state of the command is done.

How can I help you, I could give you access to logs and tests.

regards

**Comment by TrogloGeek** [comment]
Hi, this issue is 99% of time related to Prestashop maintainance mode being activated or another kind of IP access restriction. For silence response to work you must allow bank servers IP to access your website.

Does this response fit to your case?

**Comment by loran750** [comment]
hi

no, I've turned around. I've checked : 
- no maintenance mode, no IP limitation no htaccess/htpassword protection
- there is no access to /module/tggatos/silentresponse in logs (not in 404 nor in access) ... this may be the key problem ?
- website and /module/tggatos/silentresponse?DATA=<big number> accessible from anywhere (I used weproxy by direct access)

ps : the silentresponse url and the website are in http, the dev website is not accessible by SSL (no configuration yet, i don't need it), but as silentresponse is in http and nothing is in https, it may not be the problem.

pps2 : i got a problem on the DATA if i want to include CSS, i'll open another issue later : <USE_CSS>;http://xxxxxx/yyyy/file.css</USE_CSS>;    is curiously not kept, the tags disappear.

## regards

## DEBUG BEFORE

Pathfile
Reading pathfile (/home/xxxxxxxxx/.SOCIETEGENERALE/param/pathfile) OK
D_LOGO (/modules/tggatos/images/card_logo/)
F_DEFAULT (/home/xxxxxxxxx/.SOCIETEGENERALE/param/parmcom.sogenactif)
F_PARAM (/home/xxxxxxxxx/.SOCIETEGENERALE/param/parmcom)
F_CERTIFICATE (/home/xxxxxxxxx/.SOCIETEGENERALE/param/certif)

System
Reading F_DEFAULT (/home/xxxxxxxxx/.SOCIETEGENERALE/param/parmcom.sogenactif) OK
Reading F_PARAM (/home/xxxxxxxxx/.SOCIETEGENERALE/param/parmcom.yyyyyyyyyyyyyyyy) OK
Reading F_CERTIFICATE (/home/xxxxxxxxx/.SOCIETEGENERALE/param/certif.fr.yyyyyyyyyyyyyyyy) OK
Version du certificat = 01/07/2014 (SOGENACTIF)

CALL URL
https://paiement.sogenactif.com:443/cgis-payment-sogenactif/prod/callpayment

Request sent to the Payment Server
API_VERSION (P615)
CERTIFICATE_DATE (20140701)
CERTIFICATE_EXPIRED ()
CERTIFICATE_VERSION ()
CERTIFICATE_TYPE ()
BROWSER_TYPE ()
MERCHANT_ID (yyyyyyyyyyyyyyyy)
MERCHANT_COUNTRY (fr)
AMOUNT (8629)
TRANSACTION_ID (37)
CURRENCY (978)
TRANSMISSION_DATE (20140716202307)
PAYMENT_MEANS (CB,3,VISA,3,MASTERCARD,3)
HEADER_FLAG (yes)
LANGUAGE (fr)
RETURN_URL (http://dev.xxxxxxxxx.fr/modules/tggatos/autodispatch/userreturn.pub.php)
CANCEL_URL (http://dev.xxxxxxxxx.fr/modules/tggatos/autodispatch/userreturn.pub.php)
AUTO_RESPONSE_URL (http://xxxxxxxxx/module/tggatos/silentresponse)
RETURN_LOGO ()
CANCEL_LOGO ()
SUBMIT_LOGO ()
LOGO ()
LOGO2 (merchant.gif)
ADVERT (sg.gif)
CARD_LIST ()
TRANSACTION_CONDITION (SSL)
ORDER_VALIDITY ()
MERCHANT_LANGUAGE (fr)
BGCOLOR (ffffff)
TEXTCOLOR (000000)
TEXTFONT ()
BACKGROUND ()
RECEIPT ()
CADDIE ()
CUSTOMER_ID (3)
CUSTOMER_EMAIL (zzzzzzzzzzzzz)
DATA (http://xxxxxxxxx/themes/default-bootstrap/css/sogenactif/sogenactif.css)
RETURN_CONTEXT ()
TEMPLATE ()
CUSTOMER_IP_ADDRESS (109.190.86.53)
ORDER_ID (37)
CAPTURE_DAY (0)
CAPTURE_MODE (AUTHOR_CAPTURE)
STATEMENT_REFERENCE ()
CUSTOMER_PHONE ()
CONFIRM_TEMPLATE ()
BLOCK_ALIGN (center)
BLOCK_ORDER (1,2,3,4,5,6,7,8)
TARGET (_top)

---

## DEBUG AFTER PAIEMENT BUT ON SOGENACTIF SITE
- in the the shopping cart page, the cart is still not paid
- in the command page, not recorded
- no trace

---

## DEBUG AFTER RETURN TO THE MERCHANT

merchant_id: zzzzzzzzzzzzzzzzzzzzzzzzzz
merchant_country: fr
amount: 8629
transaction_id: 37
payment_means: VISA
transmission_date: 20140716202307
payment_time: 222619
payment_date: 20140716
response_code: 00
payment_certificate: 3fc58dfe9acc
authorisation_id: 415116
currency_code: 978
card_number: 4972.17
cvv_flag: 1
cvv_response_code: ??
bank_response_code: 00
complementary_code: 00
complementary_info: CARD_COUNTRY=FRA,,
return_context: 
caddie: 
receipt_complement: 
merchant_language: fr
language: fr
customer_id: 3
order_id: 37
customer_email: yyyyyyyyyyyyyyyyyyyy
customer_ip_address: 109.190.86.53
capture_day: 0
capture_mode: AUTHOR_CAPTURE
data: http://xxxxxxxxxxxx/themes/default-bootstrap/css/sogenactif/sogenactif.css

**Comment by TrogloGeek** [comment]
If you do not see the request in access log it means that the module did not had a chance to handle it. Check that your domain is publicly routable and that the zone file propagation is complete (I love the tool http://whatsmydns.net to check this).

About the CSS tag, it has probably been interpreted by your browser as an HTML tag and therefore does not appear as text. Do you see it in your response log?

**Comment by loran750** [comment]
Hi

Finally, I got SOGENACTIF support and then my Hosting company support.
It appeared that the IP from Sogenactif were blocked, as a result of a DDoS suspicion attack...
The hosting company whitelisted the IPs and now it's okay.

Oh my god... all thoses little things. I spend too many times for that.

About the CSS tag, i wrote directly in the database because the tags where always removed from the backoffice tggatos form. It's not ok yet
Anyway, I'll check that in the following days.

This issue can be closed.
Thank you very much.
