### ISSUE TITLE
only RC versions ?

### ISSUE THREAD

**Issue by martialgallorini** [TrogloGeek/prestashop-tggatos-module#34]
Hello, and thanks a lot for your efforts in developing such a module !
I can only see RC branches of your module here in github... isn't there any Stable release ?

thanks you very much

**Comment by tucoinfo** [comment]
Yes this is great work. You should try it. I have it running in production on 2 x 1.5 and one 1.6. See Readme for link to author's blog ans more positive feedback.

**Comment by martialgallorini** [comment]
Ok thanks for the feedback. But i was wondering why there isn't any stable version and if yes, where to find them ?

**Comment by tucoinfo** [comment]
Same thing for me and you should always test any release first for compat with your setup. Official reply is up to TrogloGeek.

Cheers

**Comment by TrogloGeek** [comment]
Hi, you should take a look on the Readme ;-)
https://github.com/TrogloGeek/prestashop-tggatos-module#release-cycle

Releases can be found in the releases tab (yeah, I totally like being original)
https://github.com/TrogloGeek/prestashop-tggatos-module/releases
but you should not count on it as I often forgot to package a release (in fact a strong RC makes people not to create issues tickets so I forget about this project...).
If you use this, just watch the project on GitHub and pay attention to new created issues which could bring your attention on problem you would not have found by yourself and to new commits. Should you update or not? Just have a look on commit details: does it fixes a feature you are using (or considering to) or a security/stability hole?

I totally agree with @tucoinfo, it can help to have my thoughts about stability but please make your own idea.

**Comment by martialgallorini** [comment]
Ok my bad ! i'm not used to github... and when i get source code i usually get the stable branch of it. I didn't ever notice there was a release tab !

Sure enough i will give it a try and as usual i will test the module before it integrates my production site.

Thanks a lot for your work.
