### ISSUE TITLE
Logs in the customer messages 

### ISSUE THREAD

**Issue by internetdynamique** [TrogloGeek/prestashop-tggatos-module#37]
In the BO, in the customer messages the logs from the atos transaction are listed for each order.
How can I not display them in the order tabs and in the notification by mail ? Thanks

![logs](https://cloud.githubusercontent.com/assets/14977705/10280288/5d04c614-6b6c-11e5-9111-33c3a573b035.jpg)

**Comment by TrogloGeek** [comment]
Hi,

this is a bug from a recent version of PrestaShop, I did not yet take time to identify when (I heard it came from 1.6.1.0 or 1.6.1.1, did not verify) and if fixed. It does not only affect this module but any payment module creating message associated with the order to be displayed in BO.

**Comment by tucoinfo** [comment]
I have always had this behaviour, just like we get the PayPal return status here. Personally I prefer it this way. Checked on 1.5.4.1, 1.6.0.14, 1.6.1.1
