### ISSUE TITLE
Improvement - Translations are not named according to the module name

### ISSUE THREAD

**Issue by Arkhee** [TrogloGeek/prestashop-tggatos-module#4]
When trying to translate the module, it took me some time to find the right group to translate because the name of the group did not include "tggatos".

Currently the translations are referenced under the exact name of the view : payment_failure, payment_redirect_to_bank, param_receipt_complement, payment, payment_return

But these views already exist as they are very generic, for instance the "payment_return" view is used 6 times (with my installation) which makes it hard to find the right translation.

These views shoud be prefixed with "tggatos_" if possible, making it easier to locate and translate the module in other languages.

**Comment by TrogloGeek** [comment]
This is a pure PrestaShop issue with Translations administration panel that should be submitted to @PrestaShop, not here.
Prefixing views with module name is not a good idea as it increase maximum file's path length, causing potential issues with file systems limitations.

Views are actually grouped by module
![tggatos_translate](https://f.cloud.github.com/assets/3205686/202279/f0e3819c-810c-11e2-93f2-e5d85e87d7e7.png)

Indeed it would be better to have a module's name reminder in each fieldset but you can identify to which module a template translation fieldset belongs this way.
