### ISSUE TITLE
Interoperability trouble when call outside FO/BO

### ISSUE THREAD

**Issue by e-gaulue** [TrogloGeek/prestashop-tggatos-module#41]
Dear developers,

We have external applications (SAGE) that automatically request status change from a module.

In some case, this leads to `Module::getInstanceByName($order->module);` being called from `changeIdOrderState`. At end `TggAtos` construct is called and get to:

```
        if ($this->context->employee instanceof Employee
                && $this->context->employee->isLoggedBack()
                && ($this->context->controller instanceof AdminModulesController)
                && !in_array($this->name, explode('|', Tools::getValue('configure', ''))))
        {
            $this->autoCheck();
        }
```

where `isLoggedBack` looks for password in the cookie...

But our scripts are launched through curl style mechanisms, leading to having no password as we have no cookie.

Could you consider, this code in next version:

```
        if ($this->context->employee instanceof Employee
                && ($this->context->controller instanceof AdminModulesController)
                && $this->context->employee->isLoggedBack()
                && !in_array($this->name, explode('|', Tools::getValue('configure', ''))))
        {
            $this->autoCheck();
        }
```

Or even put all the employee tests at the end.

Best regards, EG

**Comment by TrogloGeek** [comment]
Do you have the problem with the RC_4.0.0 version?

https://github.com/TrogloGeek/prestashop-tggatos-module/blob/RC_4.0.0/tggatos.php#L235

**Comment by TrogloGeek** [comment]
there will probably be no more 3.x version update
