### ISSUE TITLE
Payment Error > still a validation message

### ISSUE THREAD

**Issue by agnesdennetiere** [TrogloGeek/prestashop-tggatos-module#42]
Hello,

I just realized that when the payment does not work, (example: 3 false card info), we are still redirected to the "order confirmation" page with this message: 

_Your order has been recorded. 
We will process your order as soon as possible._

Any idea ?

Thank you.

**Comment by TrogloGeek** [comment]
Hello

This should happen only when you configure an order status for erroneous
payments in module configuration.

If you set it to "No order creation" you will instead obtain a payment
failure page which will allow the client to choose payment method again.
Le 7 janv. 2016 17:00, "Agnès Dennetiere" notifications@github.com a
écrit :
