### ISSUE TITLE
Trouble With Installation // ARM Architecture ??

### ISSUE THREAD

**Issue by olivier1208** [TrogloGeek/prestashop-tggatos-module#43]
Version PS 1.6.1.3
Version TggAtos : 4.0
Version PHP : 5.6.4-4ubuntu6.3
Système : Linux 330345-php56 4.2.0-253 #1 SMP Mon Sep 21 10:35:56 UTC 2015 armv7l
Serveur http : NC

Bonjour,

Je suis vraiment perdu et ne trouve aucune solution à mon problème.

Voilà, toute la configuration du module est OK mais le mode DEMO ne fonctionne pas ni aucun test en préprod.
Je me retrouve toujours avec le fameux : » Le paiement par carte est indisponible jusqu’à demain, nous vous prions d’accepter nos excuses pour cet inconvénient. »

Il apparait que toutes les erreurs dans la liste :
Author
TrogloGeek
1. An error log file exists, please read file `/var/www/monsite.com/www/logatos/error.log` and archive it to stop seeing this warning.
2. You are still in demonstration mode.

J’ai également, le 3. et le 4. qui apparaissent mais qui n’ont rien à côté.

Je pense donc très probablement que cela est issu des Binaries, mais ne sais pas comment le résoudre.
Concernant le log j’ai ca

severity 4/var/www/monsite.com/www/modules/tggatos/tggatos.php(738): Error when calling request ATOS binary, exit code was: 2 debug object: TggAtosModuleSystemCall Object ( [command] => /var/www/monsite.com/www/modules/tggatos/bin/request ‘language=fr’ ‘merchant_id=014022286611111′ ‘currency_code=978′ ‘amount=386′ ‘pathfile=/var/www/monsite.com/www/param/pathfile’ ‘normal_return_url=http://monsite.com/modules/tggatos/autodispatch/userreturn.pub.php’ ‘cancel_return_url=http://monsite.com/modules/tggatos/autodispatch/userreturn.pub.php’ ‘automatic_response_url=http://monsite.com/module/tggatos/silentresponse’ ‘customer_ip_address=82.66.59.155′ ‘customer_email=olivier@monsite.com’ ‘transaction_id=8′ ‘payment_means=CB,3,VISA,3,MASTERCARD,3′ ‘capture_mode=AUTHOR_CAPTURE’ ‘capture_day=0′ ‘customer_id=2′ ‘order_id=22′ [output] => Array ( ) [exit_code] => 2 [last_line] =>

Je ne sais vraiment plus quoi faire .
J’ai tout essayé en vain.

Je précise que mon hébergeur indique : « Je vous confirme que l’éxecution est possible toutefois, il faudra voir avec ATOS pour un système linux 64bit pour une architecture ARM, ce dernier point est important « .

Je ne sais pas du tout si les fichiers fournis par la banque sont compatibles.
Voici le nom du dossier Banque : webaffaires_617_PLUGIN_linux64-2.6.18

Je vous remercie infiniment de l’aide que vous pourrez m’apporter.

Très Cordialement,

Olivier

**Comment by olivier1208** [comment]
_@_
Je rajouterais que je n'ai pas de fichiers avec extension .exe pour mes executables.

++

Merci A TOUS D'avance:!

**Comment by tucoinfo** [comment]
Ca sent des binaires compilés pour x86 et non pas l'architecture ARM. Pas certain que la banque en fournisse mais je pense qu'il faut commencer par ça.

**Comment by TrogloGeek** [comment]
Bonjour,

il vous suffit de contacter votre banque en indiquant votre kernel/architecture pour que celle-ci vous fournisse les binaires adaptés à celui-ci, s'ils existent. Votre hébergeur vous avait donné les bonnes instructions ;-)

Concernant les fichiers ".exe" ceux-ci sont pour Windows, inutiles dans votre cas.

**Comment by olivier1208** [comment]
Bonsoir;

Alors avant tout....MERCI pour vos réponses rapides ca fait chaud au coeur.

@tucoinfo :+1: La banque ne m'a fourni que les versions suivantes pour les demos : 
Plugin (PHP) : Linux 32 & 64, Win 32 & 64, 
DOTNET
JAVA

Je ne vous cache pas que je maitrise peux cettre programmation.

@TrogloGeek :+1: J'ai eu la banque en ligne qui ne me donne que ces informations la.

Au passage, j'avais vu un module ATOS en Perl, mais mon hebergeur ne supporte non plus pas le Perl.

Que puis-je faire ?

Comment alors résoudre ce problème ?

Merci BEAUCOUP

**Comment by tucoinfo** [comment]
Perso je changerais d'hébergement. Cela implique de faire le bon choix et de prévoir une migration maitrisée avec un minimum de downtime. Mes clients ne regardent plus en arrière après.

**Comment by TrogloGeek** [comment]
Les modules Perl pour ATOS/SIPS ne servent qu'à contourner des restrictions sur la fonction exec() de PHP pour appeler le binaire SIPS, dans ce cas le PHP appelle Perl qui appelle le binaire : plus compliqué, plus fragile et inutile dans votre cas (il vous faudra quand même un binaire compatible avec votre système).

> Linux 32 & 64, Win 32 & 64

Vous êtes bien sous linux 64bits, votre architecture est ARM, et non x86 ou x86_64 (appelé aussi amd64) comme les binaires fournis généralement par la banque. Vous devez donc demander à la banque de clairement vous répondre : peuvent-ils vous fournir une version Linux 64bits ARM 7, oui, ou non (il faut être TRES insistant avec eux : au début vous avez généralement en ligne un technicien hotline niveau 1 (traduction : quelqu'un qui connait aussi bien que vous le sujet, voir moins, il a juste une documentation légère à sa disposition pour vous répondre), il faut insister pour monter en hotline niveau 2 minimum pour les réponses un peu moins bateau (les niveau 1 servent à filter les demandes : "est-ce que votre ordinateur est bien branché ?").

Soit la banque vous fourni le bon binaire, soit vous devrez changer d'hébergement (ou éventuellement voir s'il est possible d'émuler du x86 ou x86_64 sur votre système, mais attendez vous à du challenge si ce n'est pas le technicien hébergeur qui s'en occupe), soit il faudra changer de passerelle de paiement ou d'hébergement.

SIPS est LARGEMENT obsolète, c'est une solution des années 90 (voir avant ?) patchée et repatchée pour qu'elle puisse continuer à fonctionner de nos jours, mais elle n'est plus alignée avec la réalitée actuelle informatique.

**Comment by tucoinfo** [comment]
Damien a raison, il reste encore la possibilité d'un mode compatibilité (perso je suis sous FreeBSD en mode compat avec un les binaires Linux sans aucun souci).

**Comment by olivier1208** [comment]
@TrogloGeek 
Merci pour cette réponse étoffée.
Dans un premier temps, nous sommes donc d'accord que le problème vient bien des binaires ?
Ensuite, je les contacterais demain (WebAffaires - Credit du Nord) afin de voir avec eux si cette solution peut être apportée.
En parallèle, j'ai également demandé à l'hébergeur comment s'y prend-t-il pour les clients sous PS qui utilisent du ATOS, je vous tiendrais informé.
Alternativement, quelle passerelle de paiement me conseillerez vous alors ?
Enfin, il reviendrait donc au même d'acheter un module ATOS car la configuration ne passerait donc pas.
Merci TGG

**Comment by olivier1208** [comment]
@tucoinfo Merci !
Mais je ne maitrise que peux cela et risque de bien me planter :-1:

**Comment by TrogloGeek** [comment]
> Dans un premier temps, nous sommes donc d'accord que le problème vient bien des binaires ?

Plus précisément d'une incompatibilité entre votre architecture processeur et les binaires.
Les binaires doivent être compilés pour le bon système (kernel) et la bonne architecture CPU.

> Enfin, il reviendrait donc au même d'acheter un module ATOS car la configuration ne passerait donc pas.

A priori non, mais j'ai entendu une rumeur selon laquelle SIPS devait publier une nouvelle version de la partie marchande de leur infrastructure de paiement par internet qui n'utiliserait plus de binaires pour le chiffrement des transactions mais je n'ai rien trouvé lors de mes précédentes recherches, donc rien ne semble confirmer. Mais si tel était le cas, un module SIPS implémentant la méthode binary-less résoudrait votre problème.

@tucoinfo ici on ne parle plus de simple compatibilité pour exécuter du x86/x86_64 sous ARM, faire fonctionner des binaires d'un système (ex: linux) sous un autre (ex: FreeBSD) est bien plus "simple" : les instructions CPU sont les bonnes, seuls changent l'encapsulation de ces instruction et les bibliothèques système. Les instructions CPU disponibles sous x86/x86_64 et ARM ne sont pas les mêmes, une émulation de l'un dans l'autre, faire tourner un exécutable pour l'un sur l'autre nécessite soit une traduction à la volée de ces instructions, soit utiliser un CPU virtuel (logiciel) pour l'émulation. Quelque chose dans lequel on ne se lancera pas tête baissée sans connaissances techniques adéquates surtout lorsqu'il est question de la sécurité monétique. Encore, eut-il été question d'émuler de l'ARM sous x86 cela aurait je pense été bien plus simple (ARM n'offre qu'un jeu restreint d'instructions simples) mais l'inverse nécessite une couche d'émulation plus complexe.

> Alternativement, quelle passerelle de paiement me conseillerez vous alors ?

Désolé, ma culture dans le domaine est très limitée. J'ai développé ce module car j'ai bon nombre d'expérience avec SIPS (lors de mes premières années professionnel j'avais passé quelques temps à débugger et corriger le module SIPS communautaire pour osCommerce) et j'avais une bonne connaissance du codebase PrestaShop 1.2 et 1.3 pour avoir eu à corriger pas mal des bugs des ces versions pour des clients. Au delà de cela, mes experiences en autres passerelles de paiement sont trop marginales pour avoir une valeur de conseil, désolé, il vous faudra réunir des avis éclairés à la fois de techniciens usités à ces méthodes de paiement pour la fiabilité/solidité/simplicité et de marchands (pour les fonctionnalités vitales à votre business, niveaux de garanties des transactions face à la fraude...).

**Comment by olivier1208** [comment]
Bonjour,

La banque m'indique que les binaires Linux 64 devraient fonctionner (La dame au tel ne voulait pas lacher la morceau!)
Elle m'a proposé alternativement d'utiliser JAVA.
Est ce possible ?
Celle-ci va également m'envoyer une check list de vérifications.

Je vous tiens au courant.

Bonne journée !

**Comment by olivier1208** [comment]
Bonjour encore...

Je desespère vraiment.

Etes vous sur que l'error de calling request est bien liée à l'architecture des bin ?

Peut être que je me suis trompé quelque part au niveau de la config ?

Si j'essaye en mode démo même avec n'importe quelle certificat, rien ne marche .

Est ce normal ?

Cordialement,

**Comment by TrogloGeek** [comment]
> Elle m'a proposé alternativement d'utiliser JAVA.
> Est ce possible ?

Hmmm, il me semble que le plugin Java de SIPS utilise lui aussi les binaires pour assurer les chiffrement/déchiffrement des demandes/réponses de transaction ? Donc à priori ça ne changerait rien... Cela dit je veux bien que vous m'envoyiez leur plugin Java au cas où je me tromperais...

> Etes vous sur que l'error de calling request est bien liée à l'architecture des bin ?

En cas de doute le meilleur moyen d'être sur est de lancer les binaires via un shell sur le serveur : ils fonctionnent, ou non ;-)

> Si j'essaye en mode démo même avec n'importe quelle certificat, rien ne marche .

Aucune transaction ne peut fonctionner sans les binaires puisqu'ils assurent l'encapsulation/décapsulation des messages échangés avec les serveurs monétiques SIPS.

**Comment by TrogloGeek** [comment]
> La banque m'indique que les binaires Linux 64 devraient fonctionner (La dame au tel ne voulait pas lacher la morceau!)

Je décline toute responsabilité en cas d'incompétence de la hotline bancaire ;-)

**Comment by olivier1208** [comment]
Bonjour,

Je suis en train de me demander si je dois configurer les pathfile directement ou si c'est fait directement via votre module.

Ci dessous les api qu'ils me proposent.

[api et documentations_Webaffaires.xlsx](https://github.com/TrogloGeek/prestashop-tggatos-module/files/96227/api.et.documentations_Webaffaires.xlsx)

Honnetement je cale complètement car je viens de tester sur un autre serveur dont la config est ; 

```
Linux sl1.seolite.eu 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64 
```

Et ca ne marche pas mais je n'ai pas de log non plus !!

Je desepère :(

Merci

**Comment by olivier1208** [comment]
Cher TGG,

Je vous remercie d'avance pour tout.
Ensuite, pour lancer le shell je ne peux pas car je suis en hébergement mutualisé.
Donc aucune marche de manoeuvre.
Enfin, je ne m'y connais que très peu.

Merci de l'aide apportée....vraiment.

**Comment by olivier1208** [comment]
@TrogloGeek : je peux vous créer un accès PS et FTP et vous pouvez jeter un coup d'oeil

**Comment by TrogloGeek** [comment]
Désolé pour le délai, j'étais perdu dans un espace pentadimensionnel, accaparé par mon poste actuel.

Avez-vous pu résoudre votre problème ?
Dans le cas contraire vous pouvez m'envoyer des accès à l'adresse email associée à mes commits ou à l'adresse email que vous trouverez à cette adresse : http://www.capillotracteur.fr/ (le CV n'est pas à jour mais l'adresse email est bonne).

Je ne transmets pas l'adresse en clair ici pour éviter qu'elle ne soit récupérée par des robots.
