### ISSUE TITLE
appel d'URL reste en mode DEMO

### ISSUE THREAD

**Issue by pvl11** [TrogloGeek/prestashop-tggatos-module#48]
J'utilise le service ScelliusNet de la Banque Postale. Ce service fonctionne déjà depuis plusieurs années sur un autre site.
En passant le module en mode Production, lorsqu'on clique sur le logo du paiement par carte, le site continue à rediriger vers le mode démo :
CALL URL
https://scellius.lapostefinance.fr/cgis-payment-scellius/demo/callpayment
Comment résoudre ce problème ?

**Comment by TrogloGeek** [comment]
Merci d'indiquer vos versions de PrestaShop et du module.

L'URL est déterminée lors de la génération du formulaire avec les logos de paiement, si vous cliquez sur un logo de carte de paiement sans rafraîchir la page et que celle ci a été générée avant le changement du mode alors ce comportement est normal.

Cordialement,
Damien

**Comment by pvl11** [comment]
Les versions sont les suivantes 
Prestashop  1.6.1.1
Tggatos 3.4.0
J'ai fait un rafraichissement ainsi qu'un vidage du cache. Comment puis-je vérifier l'enregistrement du passage en production ? en DB ou sur un fichier ?

**Comment by TrogloGeek** [comment]
Il suffit de quitter la page de configuration et de revenir dessus, si le formulaire affiche la bonne valeur c'est qu'elle a été enregistrée correctement. (le module stocke les paramètres dans la table configuration de prestashop)

**Comment by pvl11** [comment]
existerait-il une raison pour laquelle l'url reste bloquée en mode demo ? Il y a des conditions autres que le flag "demo" ? Si oui, est-ce que le contenu du fichier certif.fr.xxxxxxx rentre dans ces conditions ? Pouvez-vous me dire ou se trouve le code permettant la création de l'url ?

**Comment by TrogloGeek** [comment]
Le module ne génère pas l'URL, cette URL est déterminée par l'API SIPS à partir du certificat (le fichier  certif.fr.xxxxxxx), du point de vue du module, la bascule entre démonstration et production ne change que le fichier certificat qui est envoyé en paramètre à l'API SIPS. Donc effectivement, si vous avez mis un certificat de démonstration en tant que certificat de production, votre production sera une démonstration.

**Comment by pvl11** [comment]
J'utilise un certificat qui fonctionne depuis plusieurs années sur un de mes autres sites. Je m'étonne à présent, en examinant son contenu, qu'il contient 2 fois le mot "DEMO"..., car pourtant il tourne bien ailleurs !

**Comment by pvl11** [comment]
J'utilise un certificat qui fonctionne depuis plusieurs années sur un de mes autres sites. Je m'étonne à présent, en examinant son contenu, qu'il contient 2 fois le mot "DEMO"..., car pourtant il tourne bien ailleurs !

**Comment by TrogloGeek** [comment]
Le type de certificat est normalement inscrit dans les 3 dernières lignes du certificat. S'il y a écrit DEMO alors vous n'avez probablement pas récupéré le bon certificat depuis votre site internet ;-).

**Comment by pvl11** [comment]
J'ai bien revérifié tout ça... et d'ailleurs je n'ai qu'un seul certificat sur le site en prod. Et bien, aussi curieux que cela puisse paraître, mon certificat DEMO fait tourner un site depuis plus de 3 ans ! Je contacte Atos lundi...

**Comment by TrogloGeek** [comment]
Je reste sceptique, il y a effectivement une part impressionnante de l'API SIPS qui n'est pas documentée, mais je n'ai jamais vu un certificat de démonstration pouvoir servir à de la production. Étes-vous certain de ne pas être passé à côté d'un certificat au format PHP ? (certif.yy.xxxxxxxxxxxxx.php).

Ma curiosité en est piquée au point que j'aimerais bien jeter un coup d'oeil à l'ancien site ;-)

**Comment by pvl11** [comment]
J'ai demandé un nouveau fichier config.fr. et tout à l'air de fonctionner à présent... N'empêche, mon autre site fonctionne avec un fichier démo, malgré tout...
En tout cas, je tiens à vous remercier pour le travail extraordinaire que vous avez accompli et tout particulièrement pour la mise à disposition gratuite de cet effort ! Bravo à vous.
