### ISSUE TITLE
Traduction Française

### ISSUE THREAD

**Issue by antaur59** [TrogloGeek/prestashop-tggatos-module#5]
Bonjour,

Pour ceux qui veulent la traduction du module en test en Français :

http://tinyurl.com/aghbhlv

Antoine

**Comment by emily-d** [comment]
Merci. Quelques corrections :

Récapituatif => Récapitulatif 
commercant => commerçant
Votre paiement à été accepté => Votre paiement  a été accepté

**Comment by Guiom21** [comment]
Bonjour,

merci malheureusement le fichier n'est plus dispo.

Possibilité de le remettre en DL quelque part SVP

**Comment by kyzz** [comment]
non le fichier est téléchargeable.

pour l'installer voir http://doc.prestashop.com/display/PS15/Les+traductions+dans+PrestaShop+1.5#LestraductionsdansPrestaShop1.5-Traductiondesmodulesinstallés

**Comment by Guiom21** [comment]
Bonjour,

Moi j’ai ça quand j’essaye de le charger sur http://www.envoyercefichier.com http://www.envoyercefichier.com/  :

Erreur

Le fichier demandé n'existe pas.

Mais je n’ai pas de compte chez eux je choisi l’option gratuit :

Caractéristique

Premium

Gratuit

Vitesse de téléchargement

1073741824KO/s

1073741824KO/s

Upload filesize

2050.39978027 MO

100 MO

Espace disponible

2047.99999905 MO

1024 MO

Les fichiers inactifs seront supprimés après

expiration du compte

10 Jour(s)

Peut être que cela vient de ça ?

En tout cas si quelqu’un pouvait me les faire passer ce serait très aimable !

Cordialement,

Guiom.

De : kyzz [mailto:notifications@github.com] 
Envoyé : vendredi 7 juin 2013 11:30
À : TrogloGeek/prestashop-tggatos-module
Cc : Guiom21
Objet : Re: [prestashop-tggatos-module] Traduction Française (#5)

non le fichier est téléchargeable.

je cherche à l'installer actuellement

**Comment by kyzz** [comment]
Voila le fichier avec les corrections : http://paf.im/zeaNM

**Comment by Guiom21** [comment]
Merci bien, c’est gentil.

De : kyzz [mailto:notifications@github.com] 
Envoyé : vendredi 7 juin 2013 12:01
À : TrogloGeek/prestashop-tggatos-module
Cc : Guiom21
Objet : Re: [prestashop-tggatos-module] Traduction Française (#5)

Voila le fichier avec les corrections : http://paf.im/zeaNM

**Comment by theben22** [comment]
Merci kyzz.

**Comment by TrogloGeek** [comment]
The bugtracker is not the best place to this discussion, you should store it on a github project.
