### ISSUE TITLE
Erreur - aucun frais de livraison 

### ISSUE THREAD

**Issue by AWS-Europe** [TrogloGeek/prestashop-tggatos-module#51]
Bonjour, nous avons un soucis sur notre site, lorsque le paiement s'effectue, ça part vers la plateforme wordline, puis au retour, la commande se valide mais les frais de livraison ne sont plus présents. Du coup, toutes les commandes et les factures sont faussés. Avez-vous déjà eut ce problème ?

Version module : Carte bancaire avec SIPS/ATOS v4.0.0 - par TrogloGeek
Version Prestashop : 1.6.1.2

**Comment by TrogloGeek** [comment]
Bonjour,

je suspecte que le problème vienne d'un module de transport greffé sur le hook de validation de commande qui utiliserait les données de session pour mettre à jour les informations de livraison en se basant sur le contexte utilisateur (cookie, session), hors ce contexte n'existe pas lorsque le serveur bancaire appelle directement la boutique pour valider la commande. Un moyen "simple" et rapide pour vérifier cela est de bloquer la réponse automatique (en paramétrant un domaine de réponse automatique erroné par exemple) et de voir si le même problème se produit alors.

**Comment by AWS-Europe** [comment]
Nous vous remercions pour la réponse. Nous avons solutionné le problème. Il s'agissait d'un override créé par un module de transport. Merci encore.

**Comment by TrogloGeek** [comment]
Merci pour ce retour, pourriez-vous nous indiquer de quel module il s'agit, si cela peut aider des personnes arrivant ici via une recherche Google ?
