### ISSUE TITLE
Remontée de transactions en double dans google analytics

### ISSUE THREAD

**Issue by agnesdennetiere** [TrogloGeek/prestashop-tggatos-module#53]
Bonjour,

sur les commandes payées grâce votre module (et sur aucune des commandes payées avec le module paypal) certaines anciennes commandes sont regénérées dans google analytics avec une quantité a 0, ce qui pose des problèmes car le CA dans google analytics n'est plus du tout bon.
Avez-vous une idée si ce problème peut venir de notre module ? 

Merci beaucoup
Cordialement,
Agnès

**Comment by TrogloGeek** [comment]
Bonjour,
- **Quelles versions de PrestaShop et du module utilisez vous ?** 
- **Utilisez vous un module pour le tracking des commandes sous Google Analytics ? Si oui lequel, et quelle en est sa version ?**
- **Les commandes dans le backoffice sont-elles correctes et comportant les bonnes informations ? Avez vous des doublons dans le back-office ? cf #46**

Le fonctionnement de la passerelle bancaire SIPS d'ATOS est quelque peu particulière : avant que l'acheteur ne soit renvoyé vers votre site marchand depuis le serveur bancaire à la fin de la transaction, le serveur bancaire envoie le résultat de la transaction directement en appelant une URL de callback (gérée par le module de paiement). Dans le lexique SIPS cela s'appelle la réponse silencieuse. L'intérêt de ceci est que si pour une raison ou une autre l'acheteur ne revient pas sur votre boutique après paiement (navigateur fermé ou défaut de sa connexion internet par exemple) vous obtenez tout de même le résultat de la transaction (attention, la réponse bancaire directe par URL de callback n'est pas totalement fiable ni garantie, le serveur bancaire essaye une seule fois et abandonne en cas de problème aussi bien du côté de votre serveur que de leur infrastructure).

Selon la manière dont fonctionne votre tracking G. Analytics, cette manière de fonctionner quelque peu particulière peut poser problème:

Si des données sont envoyées à Google Analytics lors de l’événement applicatif PrestaShop "Commande validée" ou "Statut de commande mis à jour", cela peut donc se produire dans le contexte de la réponse silencieuse. Ce contexte est exempte du contexte utilisateur puisque le "visiteur" de la page n'est pas l'acheteur mais un serveur de votre banque, d'ATOS ; ou encore, dans le cas de certaines formes de contrat VAD, d'un serveur SIPS vous étant dédié. Les données de cookie utilisateur (contenant entre autres les données du panier avant sa conversion en commande) et de session utilisateur ne sont pas disponibles pour votre code de tracking, s'il s'appuie dessus il y a alors des problèmes. Le code de tracking doit impérativement se fier aux données de la commande provenant de la base de données (via le modèle Order, ou éventuellement Cart).

Autre source de problème (générique à PrestaShop, n'étant pas particulièrement liée au fonctionnement de la passerelle de paiement SIPS):
L'acheteur peut ré-afficher plusieurs fois la page de confirmation de commande, page sur laquelle sont généralement placés les codes de tracking de commande Analytics. Si le code de tracking n'est pas suffisamment intelligent (idéalement il faut une mémoire, généralement en base de données, de ce qui a déjà été déclaré à la plate-forme Analytics pour ne pas générer d'envoie en doublon des informations de la commande) cela peut créer des anomalies lors de multiples consultations de cette page.

**Comment by TrogloGeek** [comment]
Demande de support close par absence de retour. Vous pouvez ré-ouvrir la demande pour apporter de nouvelles informations.

Cordialement,
Damien.
