### ISSUE TITLE
Mauvais chemin pour les images

### ISSUE THREAD

**Issue by Zicguy** [TrogloGeek/prestashop-tggatos-module#57]
Bonjour,

Après installation de la dernière version (RC 4.1.1) du module, certaines images n'apparaissent pas sur le front. Il semble qu'il reste quelques chemins de la forme "tggatos/images/" dans le module, alors que le chemin des images doit être "tggatos/views/img/".
Après quelques recherches, il semble que certains tpl ont les anciens chemin (ex: direct_payment.tpl).

Merci.

**Comment by TrogloGeek** [comment]
Bonjour, sincèrement désolé pour cette réponse plus que tardive, ce problème a été corrigé dans la RC_4.1.2 que j'ai oublié de mettre en version par défaut, ce à quoi je viens de remédier.

Merci pour votre feedback constructif, c'est grâce à ce type de retours que la qualité du module peut s'améliorer.

Cordialement,
Damien.
