### ISSUE TITLE
problem "Sorry, no more CB payments "

### ISSUE THREAD

**Issue by mrbighokage** [TrogloGeek/prestashop-tggatos-module#58]
Hello! Can you helm me to solve this problem. Is this promlem with my module or I need to solve it with my bank Credit du nord?
http://prntscr.com/c4fvqh

```
[error] => </TBODY></TABLE><BR><DIV ALIGN=CENTER><TABLE style="BORDER-RIGHT: #ff0000 1px solid; BORDER-TOP: #ff0000 1px solid; FONT-SIZE: 75%; BORDER-LEFT: #ff0000 1px solid; BORDER-BOTTOM: #ff0000 1px solid; font-family: sans-serif; border-collapse: collapse;" cellPadding=3 width=700><TBODY><TR style="background-color: #ff0000"><TD align=middle><B>API ERROR</B></TD></TR><TR><TD>Error reading certificate data at line  (CB56FED78EF080890036CE8384B6022EE7279FC4BE04F7E0A372CC547812CD55D3 ) </TD></TR></TBODY></TABLE><BR></DIV>
```

**Comment by TrogloGeek** [comment]
`Error reading certificate data at line  (CB56FED78EF080890036CE8384B6022EE7279FC4BE04F7E0A372CC547812CD55D3 )`

You probably did corrupt your certificate transferring it via ASCII FTP transfert.
Transfer it again using BINARY FTP transfert mode or a non destructive transfert protocole (rsync or scp).

If you use GIT or another VCS to put it online, file endings can also have been altered by it when checking out files.

**Comment by Oknel** [comment]
how can I check my certificate?

**Comment by mrbighokage** [comment]
file transferred secure method
the problem persists...
i try to get a new certificate

**Comment by TrogloGeek** [comment]
You can check your certificate by using directly the SIPS API via CLI interface, please see SIPS documentation provided by your bank for this purpose.

**Comment by TrogloGeek** [comment]
What do you call "secure method"?

**Comment by mrbighokage** [comment]
sftp | text and binary transfer settings
