### ISSUE TITLE
DATA Vide

### ISSUE THREAD

**Issue by Symediane** [TrogloGeek/prestashop-tggatos-module#62]
Bonjour,

nous venons de remarquer que lorsque nous faisons un paiement, nous sommes ensuite directement redirigés sur l'historique des commandes. D'après le code de userreturn.php, cela signifie que la variable DATA est vide. Une idée de la raison ? Est-ce que Atos a changé son fonctionnement ? Car de notre côté, le paiement est bel et bien passé.

Merci de votre réponse !

**Comment by TrogloGeek** [comment]
Bonjour,

Version PrestaShop ?
Version du module ?

L'origine de la perte du champ DATA est généralement du à une redirection (HTTP => HTTPS par exemple).

**Comment by Symediane** [comment]
Bonjour,

le prestashop est en version 1.6.0.14 et le module, 3.4.0.
Ce qui est bizarre c'est que je suis persuadée qu'avant, on passait bien par une page de confirmation (mais je ne saurais pas dire depuis quand ça ne marche plus)

**Comment by TrogloGeek** [comment]
Il se peut que le serveur vous envoie plus de données qu'auparavant (un message DATA plus long) et qu'une directive de filtrage (mod_security d'Apache ou le mod Suhosin de PHP par exemple) supprime ce champ à cause de sa longueur. Un Suhosin qui n'a pas été configuré en conséquence pose souvent ce problème.
Pour obtenir la longueur max du champ DATA il faut se tourner vers le support technique SIPS.

**Comment by TrogloGeek** [comment]
Demande de support fermée pour absence de réponse, n'hésitez pas à ré-ouvrir celle-ci pour apporter de nouvelles informations.
