### ISSUE TITLE
Le passage en SSL (HTTPS) pose problème

### ISSUE THREAD

**Issue by pvl11** [TrogloGeek/prestashop-tggatos-module#63]
Bonjour
Je passe la totalité de mes sites en SSL, donc module de paiement compris. A l'appel du module j'ai une erreur 127. A la lecture du message d'erreur je constate que le lien "automatic_response_url" est demeuré en "http", donc non sécurisé. Ce lien doit-il demeurer tel quel ? Comment le rendre en "https" ?
Merci de vos réponses

MSG ERREUR:

 TggAtosModuleSystemCall Object
(
    [command] => /kunden/homepages/2/xxxxxxxxxx/htdocs/modules/tggatos/bin/request 'language=fr' 'merchant_id=xxxxxxxxxx' 'currency_code=978' 'amount=7530' 'pathfile=/kunden/homepages/2/xxxxxxxxxx/htdocs/xxxxxxxxxx/pathfile' 'normal_return_url=https://www.site.com/modules/tggatos/autodispatch/userreturn.pub.php' 'cancel_return_url=https://www.site.com/modules/tggatos/autodispatch/userreturn.pub.php' 'automatic_response_url=http://www.site.com/module/tggatos/silentresponse' 'customer_ip_address=78.0.0.0' 'customer_email=admin@yahoo.fr' 'transaction_id=8' 'payment_means=CB,3,VISA,3,MASTERCARD,3' 'capture_mode=AUTHOR_CAPTURE' 'capture_day=0' 'data=NO_RESPONSE_PAGE' 'customer_id=1' 'order_id=161'
    [output] => Array
        (
        )

```
[exit_code] => 127
[last_line] => 
```

)

**Comment by TrogloGeek** [comment]
Bonjour,

l'utilisation de ce module nécessite la lecture de la documentation sur le système SIPS fourni par la banque.

L'erreur 127 n'a normalement strictement rien à voir avec votre migration SSL mis à part que vous avez probablement du transférer le site sur un autre serveur ou changer quoi que ce soit dans l'environnement sans mettre à jour en conséquence la configuration du module (chemins vers les binaires, paramètres et logs) ou ajuster les droits et propriétaires sur les fichiers/dossiers pour permettre à PHP d'invoquer les binaires via la fonction exec();

Concernant la réponse automatique en plain HTTP, les serveurs SIPS ne sont pas capables (du moins pour autant que je sache) de gérer le SSL pour la réponse automatique (SIPS est un dinosaure datant d'un age antique qui n'a plus pied dans les réalités actuelles de l'informatique). Cf documentation SIPS.

Cordialement,
Damien.

**Comment by pvl11** [comment]
Merci pour votre réponse. La migration SSL a été faite sur un serveur 64 bits, et il a fallu changer les fichiers exe. Tout est rentré dans l'ordre donc. Merci encore pour ce magnifique module.
