### ISSUE TITLE
Order randomly created after payment

### ISSUE THREAD

**Issue by charlesthk** [TrogloGeek/prestashop-tggatos-module#66]
Hello,

we are using your (perfect) module to handle payments on our website in production and we have an issue : the orders are not always created after the payment is made.

Many thanks. 

_Regarding the emergency of this issue, can you have a look at our website (paid service of course) ?  Thanks_

**Comment by TrogloGeek** [comment]
Hello, I apologize for answering late,

this is probably a timeout or a fatal error during the processing of PrestaShop's order hooks.

If you are still in need for help troubleshooting, you can contact me using the following email address:
troglogeek@capillotracteur.fr
