### ISSUE TITLE
Question: Is it possible to reimburse through SPIP/ATOS ?

### ISSUE THREAD

**Issue by e-gaulue** [TrogloGeek/prestashop-tggatos-module#68]
Nothing to add. Everything is in the tittle.

**Comment by e-gaulue** [comment]
It looks like on page 20 of this document: http://docplayer.fr/8570620-Guide-du-developpeur-atos-origin-sips-office-www-sips-atos-com.html

I have to think more about it.

**Comment by TrogloGeek** [comment]
Ce document fait référence à la solution SIPS Office avec laquelle ce module n'est pas compatible.
Les remboursements peuvent éventuellement être possibles via le back office de gestion des transactions fournis par votre banque, mais pas via le module. Vous pouvez éventuellement configurer le module pour utiliser un mode de capture différé pour vous permettre de valider/invalider les transaction durant la période de différé via le back office fourni par la banque.
