### ISSUE TITLE
Problems with payments after moving to https

### ISSUE THREAD

**Issue by 6120ssu** [TrogloGeek/prestashop-tggatos-module#70]
Bonjour,
nous avons un problème depuis le passage du site en https.
Le paiement se passe correctement mais l'enregistrement dans la base de données échoue.
Nous avons réussi à contourner le problème en activant l'option "Force user return from bank" mais cela ne me semble pas normal.
Avez-vous des informations et/ou des conseils en rapport avec ce comportement.
Nota : tout fonctionnait parfaitement en http

Hi
we have an issue with payments since we moved to https.
All payments succeed but nothing is stored in the database.
We were able to get around this problem by activating the optional "Force user return from bank". But I do not believe this is the correct way. Return to seller's shop should be an option.
Do you have any information or advice about this particular behaviour ?
Everything worked like a charm in http.

**Comment by TrogloGeek** [comment]
En effet, depuis PrestaShop 1.6.0.11 je crois, des modifications de FrontController ont brisé la configuration du contrôleur gérant la réponse silentieuse.
Pourriez-vous s'il vous plait tester la RC_4.1.3 ?
Le dernier patch devrait résoudre le problème, s'il ne vient pas de votre configuration de serveur HTTP.

**Comment by 6120ssu** [comment]
Comportement identique avec la RC_4.1.3

**Comment by TrogloGeek** [comment]
Il faudra que je fasse des tests mais normalement le patch de la 4.1.3 devrait suffire pour la partie liée à PrestaShop. Il faut vérifier que vous n'avez pas une règle de forçage HTTPS dans les règles de redirection du serveur HTTP (exemple RewriteRule sur Apache2) qui tente de rediriger les réponses silencieuses,  le système bancaire SIPS ne gère pas le SSL

**Comment by 6120ssu** [comment]
Merci pour votre réponse rapide.
Nous allons vérifier nos paramètres serveur.

**Comment by chOse** [comment]
Ca fonctionne en désactivant la RewriteRule de HTTP vers HTTPS !
Quel enfer ce bug !
Bon cela dit c'est étrange qu'avec le HTTPS activé par défaut sur Presta, l'URL de silentresponse qui apparaît dans le debug soit en http://

**Comment by e-gaulue** [comment]
C'est très bien expliqué par TrogloGeek dans #67 .

**Comment by TrogloGeek** [comment]
> Bon cela dit c'est étrange qu'avec le HTTPS activé par défaut sur Presta, l'URL de silentresponse qui apparaît dans le debug soit en http://

C'est voulu, sans cela la réponse silencieuse ne pourrait pas aboutir, SIPS étant un dinosaure issu d'une ère reculée de l'informatique, celui-ci n'est pas capable de gérer le SSL...
