### ISSUE TITLE
Problème de paiement => commande non créée

### ISSUE THREAD

**Issue by mathieu33370** [TrogloGeek/prestashop-tggatos-module#71]
Bonjour,
je souhaite remplacer un vieux module Atos par Tgg Atos que j'ai déjà fait fonctionner sur d'autres boutiques par le passé.
Là j'ai installé la dernière release 4.1.3 mais j'obtiens plusieurs problèmes : 
- une fois le paiement terminé j'obtiens un message "Nous attendons que la banque traite votre paiement. Nous vous enverrons un email dès réception de la confirmation.". Alors que j'ai pourtant le code retour 00 qui devrait m'indiquer que le paiement est effectué.
- aucune commande n'est créée dans Prestashop. 

Je précise que je suis en mode tunnel HTTPS sur une PS 1.5.4.0 

Merci de votre aide.

**Comment by senthilsugumar** [comment]
HI Damien VERON,

I had problem with CB card payment.  The customer has paid the amount through CB card and we received payment but the cart doesn't convert to order. The cart still present in customer account. So we create order from Backoffice. This kind of problem occurs some times (tggatos version 4.1.3). Could you please suggest a solution for this problem ? urgrent ...

**Comment by TrogloGeek** [comment]
Bonjour @mathieu33370 désolé pour l'énorme retard du à une vie professionnelle chaotique l'année passée (start-up).

A cause d'une modification récente (enfin qui l'était à l'époque de la 4.1.3) du focntionnement SIPS, il a fallu que j'implémente une gestion de lock entre les réponse utilisateurs et silencieuses pour empêcher les création de commandes en double. Le problème décrit indique que la réponse silencieuse a été reçue en premier et a capturé le lock sur la commande mais que le traitement de la réponse silencieuse n'a pas abouti, il faudrait vérifier le log d'erreur PHP/HTTP à la recherche d'une erreur ou d'un timeout.
