### ISSUE TITLE
Problème après passage en HTTPS

### ISSUE THREAD

**Issue by VincentLaisney** [TrogloGeek/prestashop-tggatos-module#72]
Bonjour,
Nous venons de passer notre site prestashop en https.
Nous avons redirigé toutes les requêtes http vers https par mod_rewrite à l'exception de celle concernant "tggatos" au moyen d'un RewriteCond:
RewriteCond %{REQUEST_URI} !tggatos

Toutes les redirections fonctionnent bien mais le retour silencieux de SIPS (silentreturn) ne fonctionne pas.

Voici ce que contient le log du rewrite pour le requête de SIPS:
[Thu Apr 20 17:29:01.129946 2017] [rewrite:trace2] [pid 26327] mod_rewrite.c(470):  - [www.traditions-monastiques.com/sid#7efde7ea0d18][rid#7efde82179a0/initial] init rewrite engine with requested uri /fr/module/tggatos/silentresponse
[Thu Apr 20 17:29:01.129962 2017] [rewrite:trace3] [pid 26327] mod_rewrite.c(470):  - [www.traditions-monastiques.com/sid#7efde7ea0d18][rid#7efde82179a0/initial] applying pattern '(.*)' to uri '/fr/module/tggatos/silentresponse'
[Thu Apr 20 17:29:01.129974 2017] [rewrite:trace1] [pid 26327] mod_rewrite.c(470):  - [www.traditions-monastiques.com/sid#7efde7ea0d18][rid#7efde82179a0/initial] pass through /fr/module/tggatos/silentresponse

Malgré le "pass through", la requête n'aboutit pas et la commande n'est pas validée.

Si nous nous connectons à l'adresse "http://www.traditions-monastiques.com/fr/module/tggatos/silentresponse" nous obtenons une erreur "Not Found
The requested URL /fr/module/tggatos/silentresponse was not found on this server."

Si vous avez une idée pour résoudre ce problème, c'est avec plaisir que nous acceptons vos suggestions.
Vincent

NB nous utilisons la version 3.4.0 de tggatos avec PS 1.6.0.6

**Comment by TrogloGeek** [comment]
Ce problème a été normalement corrigé en 4.1.3, je ferme le ticket mais vous pouvez le ré-ouvrir si le problème persiste avec cette version.
