### ISSUE TITLE
Besoin d'aide pour configurer TGG ATOS

### ISSUE THREAD

**Issue by Je-suis-David** [TrogloGeek/prestashop-tggatos-module#73]
Bonjour.
Je recherche une personne qui pourrait m'aider à réinstaller TGG ATOS.
C'est Damien qui m'avait installé gentiment le module en 2014 mais je devine qu'il doit être très occupé par sa vie professionnelle.
Le module a parfaitement fonctionner pendant quelques années (il est en version 3.4.0) mais comme les paiement en 2x et 3x ne fonctionnait plus, j'ai tenter de le réinitilaiser et là, catastrophe : le module est revenu au point de départ et il faut entièrement le configurer, ce que je ne sais pas faire.
Auriez-vous un contact à m'indiquer qui pourrait me tirer de ce mauvais pas?
Merci
Je suis en prestashop 1.6.
David

**Comment by TrogloGeek** [comment]
Salut David,
désolé effectivement l'année dernière était très mouvementée.
J'espère que tu auras pu résoudre ton problème ?
Je ferme l'issue mais tu peux la ré-ouvrir si tu as toujours besoin d'assistance.
