### ISSUE TITLE
Transaction spilt

### ISSUE THREAD

**Issue by oliveandrew** [TrogloGeek/prestashop-tggatos-module#75]
If the client places an order and pay the full amount. But in our BO the transaction amount is is split. 
For instance the client order for 65.50 euro means, the transaction will be 65,25 euro and then another transaction with 0,25 euro. This will take more time to update the second transaction. Some times it will take one week. Please help me to find a solution asap.
For your information we are using prestashop 1.5.6.1 and tggatos-module version is 4.0.0.

Thanks,
Olive

**Comment by TrogloGeek** [comment]
Version 4.0.0 is outdated, please check 4.1.3.

I'm facing difficulties understanding your issue, if your more at ease with french language you can submit it in french as well.
