### ISSUE TITLE
Error when calling request binary, system exit code: 139, text output

### ISSUE THREAD

**Issue by dngraphisme** [TrogloGeek/prestashop-tggatos-module#77]
Bonjour,  

Je reprends actuellement un Prestashop avec cette erreur sur ce module > Error when calling request binary, system exit code: 139, text output

Je vois que dans l'un de vos post il est dit de remplacer les fichiers binaries >

un code retour shell 139 signifie normalement une faute de segmentation (tentative de manipuler de la mémoire n’appartenant pas au programme). Vous avez probablement corrompu les binaires en les manipulant (je pense particulièrement à des transferts FTP en mode ASCII). Vous pouvez vérifier cela en lançant manuellement les binaires via une console SSH sur votre serveur.
Si tel est bien le problème, remplacez simplement vos binaires corrompus par des binaires sains fournis par la banque.

Est-ce la bonne démarche ?

Merci en tout cas pour le dev.

**Comment by TrogloGeek** [comment]
Bonjour,

la signification des code retour peut changer d'une distribution/kernel à une/un autre, mais de toutes manières cette procédure comportant une vérification manuelle via SSH alors oui, elle est toujours pertinente en cas de soucis avec les binaires.
