### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by agp01** [TrogloGeek/prestashop-tggatos-module#8]
Hello,

J'ai essayé d'installer le module ( RC 3.0.0 et developpement) sur Prestashop 1.5.4. L'installation se passe sans problème (Module téléchargé avec succès) mais le module n'y est pas !? 
- pas de message d'erreur dans les logs (apache & PHP)
- pas de fichiers (répertoire tgg*)  dans le répertoire modules 

Serveur sous gentoo linux : PHP 5.4.8, Apache 2.2.24 (worker) & mod_fastcgi

Merci pour ton travail, n'hésite pas à revenir vers moi si besoin de + d'information ou tests.

cheers!
agp

**Comment by ghost** [comment]
Bonjour

pour ma part j'ai tenté de le charger par le upload de module, mais en fait il faut l'installer à la main dans htdocs/modules/  et ... suivre la doc qui le raconte (RTFM),
bien mettre les bons chemins et les bons droits ensuite

**Comment by TrogloGeek** [comment]
Back office automated deployment should work, provided you have a compatible archive made out of the module, which I don't provide at the moment. How did you try to install it: 
URL download? (which URL?)
File upload? (what file, where does it comes from?)

Anyway, SIPS integration needs manual interventions (read [Installation (differences with a simple PrestaShop module)](http://github.com/TrogloGeek/prestashop-tggatos-module#installation-differences-with-a-simple-prestashop-module)), so back office installation function is somehow pointless with this module.
