### ISSUE TITLE
Segfault on request binary call

### ISSUE THREAD

**Issue by Zulgrib** [TrogloGeek/prestashop-tggatos-module#80]
Greetings, we get a segfault when running the request binary from a specific server running archlinux where i tried to overwrite the binary, using this repo as source with wget to download, also tried to fetch it from another server where the binary works.

I suspect there might be a problem with various libraries that are bleeding edge in arch and older in other distros.

Are there sources of the binary you provide on this repo to allow proper relinking with recent libraries ?
Are there some prerequisite list for libraries to be able to compile an older version specifically for the binary ?

uname -a
Linux InkConstruction 4.15.5-1-ARCH #1 SMP PREEMPT Thu Feb 22 22:15:20 UTC 2018 x86_64 GNU/Linux

file /home/---/web/---/modules/tggatos/bin/request
/home/---/web/---/modules/tggatos/bin/request: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 2.6.9, not stripped

I suspect the binary is just plain too old to work on modern systems.

**Comment by tucoinfo** [comment]
Hi there. Shouldn't you be requesting the correct and latest binaries from your payment processor?

**Comment by TrogloGeek** [comment]
Hi, you're not supposed to use the binary provided in this module which is just a placeholder to allow quick testing of the module on compatible servers, you're supposed to use the one provided by your bank.

To avoid problems with bleeding edge library versions you should grab the statically linked version of the SIPS binaries your bank provides.

Binaries are out of scope of this project which is just a connector between PrestaShop and SIPS systems, with the binaries being part of SIPS system.

To gain a better understanding of SIPS you can read integration documentation provided by your bank, it will probably be mostly outdated with PHP exemples quality you would not accept even from a trainee, but will let you know how SIPS transactions work.

**Comment by doekia** [comment]
@Zulgrib the binaries are proprietary from Atos SIP. They provide them to the various bank that are responsible for distributing them to their own customer. The source code has never been available anywhere. You are probably facing the same issue as those running ARM linux (ie: showstopper) since the binary as they exists have never been recompiled over the last 8 years.

**Comment by TrogloGeek** [comment]
I'd like to know how many of you are experiencing such troubles, as one thing that could be done is to wrap the binaries into a simple JSON/XML RPC web service so SIPS ciphering/deciphering operations could become a microservice that could be installed on a dedicated VM with a compatible system, thus giving shop integrators/owner some more options, at the cost of a more complicated architecture.

**Comment by doekia** [comment]
Here attached a set of binaries that fix the issue
They are initially marked x64_2.6.18_p615 for glibc glibc-2.5-42 and after


[x64_2.6.18_p615.zip](https://github.com/TrogloGeek/prestashop-tggatos-module/files/1881078/x64_2.6.18_p615.zip)
