### ISSUE TITLE
Certificat Mercanet non reconnu

### ISSUE THREAD

**Issue by woodyalain** [TrogloGeek/prestashop-tggatos-module#81]
Bonjour,
J'ai un souci concernant le module que je viens d'installer sur mon Prestashop 1.7 (bravo au passage à son créateur !).
J'ai suivi scrupuleusement toutes les consignes d'installation et uploadé les fichiers provenant de ma banque (BNP Mercanet). Malheureusement, le menu déroulant "Select the production certificate" reste désespérant vide ! Je n'arrive pas à sélectionner mon compte Mercanet.
Avez-vous une idée d'où vient le problème ?
Merci !

**Comment by TrogloGeek** [comment]
Bonjour, il faut que je rende cela plus clair dans la documentation mais le module a été prévu pour les certificats au format "classique", il ne faut *pas* prendre le certificat au format PHP. Si le certificat est au format classique et est bien placé dans le dossier des paramètres et correctement nommé (certif.fr.<id_marchand>) le module devrait le détecter sans soucis.

**Comment by woodyalain** [comment]
Merci Damien pour votre réponse rapide ! ;-)

J'ai bien récupéré le certificat au format classique et déposé dans le dossier param (via ftp en binaire). Mais rien n'y fait, mon certificat n'apparait pas dans le menu 'Select the production certificate'. Pour info, j'ai installé la version 5.0.0 beta 2.
Pensez-vous que je puisse installer une version plus ancienne pour voir si cela règlerait le problème ? Merci infiniment pour votre disponibilité, j'apprécie beaucoup !!!

Alain

**Comment by TrogloGeek** [comment]
Je doute qu'une version antérieure résolve le problème, le système qui liste les certificats disponible n'a pas été mis à jour depuis deux ans: https://github.com/TrogloGeek/prestashop-tggatos-module/blame/5.0.0-beta/tggatos.php#L2025

Le fichier est bien nommé "certif.fr." suivi de 15 chiffres et placé dans le dossier de paramètres configuré dans l'onglet avancé ?

**Comment by Symediane** [comment]
Bonjour,

j'ai le même problème (sur un prestashop 1.4). Le certificat est au bon format. Faut-il que le fichier ait des droits particuliers ?

Merci
