### ISSUE TITLE
Carte bancaire avec SIPS/ATOS société général

### ISSUE THREAD

**Issue by ghost** [TrogloGeek/prestashop-tggatos-module#82]
Je ne comprend pas d'ou peuvent venir ses erreurs

    Your transaction_id time zone is not set.
    Pathfile F_CERTIFICATE value is 80 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.
    Pathfile F_PARAM value is 81 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.
    Pathfile F_DEFAULT value is 92 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.
    Logs location is the default location which should be moved for security reason. Put it outside of HTTP document root and any public access folder if you can. Make sure no one who shouldn't has access to it. Do not forget to update module's config with new location in basic panel.
    ATOS SIPS parameter files location the default location which should be moved for security reason. Put it outside of HTTP document root and any public access folder if you can. Make sure no one who shouldn't has access to it. Do not forget to update module's config with new location in advanced panel.

**Comment by TrogloGeek** [comment]
> Your transaction_id time zone is not set.

Vous devez configurer la timezone utilisée par le serveur de paiement dans l'onglet avancé pour que le module sache à quelle heure le transaction_id doit être réinitialisé. Pour savoir quelle timezone saisir il faut vous tourner vers le service technique de votre fournisseur de service SIPS.

> Pathfile F_CERTIFICATE value is 80 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.
> Pathfile F_PARAM value is 81 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.
> Pathfile F_DEFAULT value is 92 characters long. An undocumented limitation of ATOS SIPS pathfile reader seems to disallow pathfile values to be longer than 78 characters. F_* values can be shortened by moving param directory upper on the file system and updating corresponding entry in advanced conf.

L'emplacement de votre boutique sur le système de fichier induit des chemins de fichier trop longs pour pouvoir être supportés par les binaires SIPS. Vous devez déplacer le dossier `param` quelque part sur le serveur où le chemin du dossier sera plus court.

> Logs location is the default location which should be moved for security reason. Put it outside of HTTP document root and any public access folder if you can. Make sure no one who shouldn't has access to it. Do not forget to update module's config with new location in basic panel.
> ATOS SIPS parameter files location the default location which should be moved for security reason. Put it outside of HTTP document root and any public access folder if you can. Make sure no one who shouldn't has access to it. Do not forget to update module's config with new location in advanced panel.

Les dossiers `log` et `param` contiennent des informations sensibles, ils devraient être déplacés quelque part sur le système de fichier où ils ne seront pas accessibles via HTTP et éventuellement les rendre inaccessibles à des prestataires techniques pouvant intervenir sur votre boutique s'ils ne sont pas suffisamment dignes de confiance.

---

Pour déplacer un dossier (`param`, `log` ou `bin`) vous devez déplacer manuellement le dossier puis saisir le nouvel emplacement de celui-ci dans l'onglet des paramètres avancés du module.
