### ISSUE TITLE
Empty order status and cart doesn't convert to order

### ISSUE THREAD

**Issue by senthilsugumar** [TrogloGeek/prestashop-tggatos-module#83]
HI Damien VERON,

i) Some orders are inserted with empty order status and it occurs randomly. Many of the customers using Sogenactif payment most of the orders are inserted correctly but sometimes few orders are inserted without order status. This kind of problem occurs with some intervals, For instance last one month i didn't have this problem. So , i think this problem has been solved but last 3 days i had this problem. (tggatos version 4.1.3 / Prestashop version 1.5.6)

ii) I had problem with CB card payment. The customer has paid the amount through CB card and we received payment but the cart doesn't convert to order. The cart still present in customer account. So we create order from Backoffice. This kind of problem occurs some times (tggatos version 4.1.3 / Prestashop version 1.5.6). Could you please suggest a solution for this problem ? urgrent ...

**Comment by TrogloGeek** [comment]
> i) Some orders are inserted with empty order status and it occurs randomly.

This often occurs with out of stock orders (back orders) provoking errors on PrestaShop handling.

> i) Some orders are inserted with empty order status and it occurs randomly.
> ii) [...] The customer has paid the amount through CB card and we received payment but the cart doesn't convert to order.

Both problems can happen when a module having a listener on order creation/update hooks raise errors. The second one can as well be related to PHP process encountering a timeout (either configured on PHP or HTTP side).
This worth checking your PHP/HTTP error logs, configuring them if necessary.

**Comment by TrogloGeek** [comment]
Re-open if new information available
