### ISSUE TITLE
Tab doesn't works for basic,single, ... tabs

### ISSUE THREAD

**Issue by ghost** [TrogloGeek/prestashop-tggatos-module#9]
because of this Uncaught TypeError: Object [object Object] has no method 'tooltip'

</script>
                   <script type="text/javascript">jQuery(function($) {
        $('#tggatoscontent').tooltip();

Uncaught TypeError: Object [object Object] has no method 'tooltip'

```
    $('#tggatosconfigtabs').tabs({ active: 0 });
        });
</script>
```

then it brokes the layout and some functionnalities, any idea how to fix it 
this is jquery ... and i 'm not comfortable with this; i figure this is just how to write quotes or something like this

**Comment by TrogloGeek** [comment]
Please read [`details about production environment configuration` section](https://github.com/TrogloGeek/prestashop-tggatos-module#release-candidate-feedback-requests) before submitting support request.
A little care formatting your request could be nice too, it is hardly readable.

The module uses a shipped jQuery UI for it's back office interface, your problem can be an incompatibility with a back office theme, if not using default, try with it. Also check that embeded jQuery UI is correctly included to the page and working.

**Comment by emily-d** [comment]
Seems to be a conflict with the new Prestashop's module Expertise/Gamification. If removed, the error disapears.

**Comment by ghost** [comment]
Yes, you're right, deactivating expertise/gamification module was in conflict, now tabs are ok, thx for the fix :-)

**Comment by TrogloGeek** [comment]
I did not know that Prestashop already embed a jQuery UI version which can be requested by modules, this is what does Expertise/Gamification and it results with a conflict between the two jQuery UI instances.
The way Expertise/Gamification instantiates a jQuery UI is the right way, TggAtos should work the same way.
