### ISSUE TITLE
A propos de la réglementatino du 14/09/2019

### ISSUE THREAD

**Issue by antoine4269ww** [TrogloGeek/prestashop-tggatos-module#99]
Bonjour,
Pour info, je souhaiterai savoir si votre module pour PS 1.6 sera compatible avec la nouvelle règlementation du 14/09/2019.
"Pour informations, à compter du 14 septembre 2019, la législation européenne exigera que les paiements en ligne encaissés par des marchands européens (Royaume-Uni inclus) et réglés au moyen de cartes bancaires émises en Europe soient fortement authentifiés. Passé cette date, les émetteurs refuseront les paiements qui ne seront pas conformes à l'authentification forte du client (SCA), sauf en cas d'exemption à la réglementation sur l'authentification forte."
Remerciements
Patrick

**Comment by TrogloGeek** [comment]
Bonjour,

ce module ne fait que le pont entre PrestaShop et le système de paiement SIPS, envoyant l'utilisateur accompagné des bonnes informations vers le serveur bancaire et traitant les informations récupérées au retour de l'utilisateur pour mettre à jour en conséquence panier et commande.

L'authentification forte est faite ou non directement sur le serveur bancaire, par la banque. Le module peut fonctionner avec ou sans cette authentification forte de manière transparente car cela est décidé par le serveur bancaire et n'affecte pas le protocole SIPS boutique/banque.

La question est donc plutôt à poser au support client de la banque avec qui le contrat VAD a été conclu.

**Comment by antoine4269ww** [comment]
Merci Damien, 
Je comptais bien aussi leur demander.
Cdlt
